__author__ = 'alexy'

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'imagekit',
    'widget_tweaks',
    'annoying',
    'ckeditor',
    'rest_framework',
    'core',
    'api',
    'landing',
    'apps.geolocation',
    'apps.dashboard',
    'apps.administrator',
    'apps.agency',
    'apps.calculator',
    'apps.correspondence',
    'apps.moderator',
    'apps.manager',
    'apps.forum',
    'apps.sale',
    'apps.distributor',
    'apps.client',
    'apps.ticket',
    'apps.packages',
    'apps.robokassa',
    'apps.stand',
    'apps.hanger_mailer',
    'django_cleanup',
)
