__author__ = 'alexy'

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'imagekit',
    'widget_tweaks',
    'annoying',
    'ckeditor',
    'rest_framework',
    'core',
    # 'api',
    # 'apps.ticket',
    'landing',
    'apps.dashboard',
    'apps.administrator',
    'apps.moderator',
    'apps.manager',
    'apps.city',
    'apps.sale',
    # 'apps.adjuster',
    # 'apps.adjustertask',
    # 'apps.surface',
    # 'apps.journal',

    # 'apps.incoming',
    # 'apps.sign',
    'django_cleanup',
)
